enableBounceBlueWitherSkull = true
enableMoreInertialBlueWitherSkull = true
enableShootMoreBlueWitherSkull = true
enableSpinAndWhiteSummon = true
enableExplodeByHalfHealth = true
enableExplodeByDie = false
enableChargeAttack = true
enableDoubleHealth = true
enableMaintainWeakenedState = true
